SHELL := /bin/bash
############PATH := $(USER)/bin:$(PATH)
BOOST_ROOT_VERSION=76
BOOST_ROOT_VERSION=78
boost.root=$(boost.root.1_$(BOOST_ROOT_VERSION)_0)
MAIN=put_variant
include $(HOME)/prog_dev/root.imk
INCS:=-I$(boost.replacements)/common -I$(boost.root) $(INCS)

